apiVersion: builtin
kind: PatchTransformer
metadata:
  name: security-context-patch
patch: |-
  [
    {
      "op": "add",
      "path": "/spec/template/spec/containers/0/securityContext",
      "value": {
        "allowPrivilegeEscalation": false,
        "capabilities": {
          "drop": ["ALL"]
        },
        "readOnlyRootFilesystem": true,
        "runAsGroup": 3000,
        "runAsNonRoot": true,
        "runAsUser": 1000
      }
    }
  ]
target:
  kind: Deployment