apiVersion: builtin
kind: PatchTransformer
metadata:
  name: security-context-patch
patch: |-
  spec:
    template:
      spec:
        containers:
        - securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 3000
            runAsNonRoot: true
            runAsUser: 1000
target:
  kind: Deployment