resources:
  - ../../base  # Pulling in the shared base configuration

patches:
  - path: patches/deploy.yaml   # Applying customizations for go-api
    target:
      kind: Deployment

commonLabels:
  app: go-api
  owner: cfa

commonAnnotations:
  cfa-base-name: go-api
