bases:
- https://github.com/chick-fil-a/kustomize-application/python-api?ref=main

commonLabels:
  app: my-k8s-api

commonAnnotations:
  cm.chick-fil-a.com/system-tag: "CAP_BLOG_POST"

namePrefix: my-k8s-api-
namespace: my-k8s-api

images:
- name: application-image-placeholder
  newName: busybox
  newTag: latest

patches:
- target:
    kind: Deployment
  path: patches/deploy.yaml