bases:
- ../backend

commonAnnotations:
  cfa-base-name: java-api

patches:
- target:
    kind: Deployment
  path: patches/deploy.yaml
- target:
    kind: HorizontalPodAutoscaler
  path: patches/hpa.yaml
