apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  labels:
    owner: cfa
    prometheus-enabled: "true"
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      owner: cfa
  namespaceSelector:
    any: true
  endpoints:
  - port: app-port
    interval: 30s
    scheme: http
    path: /prometheus
