apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default # Addition
spec:
  ports:
  - name: app-port
    port: 80
    protocol: TCP
    targetPort: app-port
  type: NodePort