name: Kustomize Overlay Test

on:
  workflow_dispatch:
    inputs:
      application:
        description: "Select application type"
        required: true
        type: choice
        options:
          - go-api
          - java-api
          - python-api
          - frontend
          - backend

jobs:
  test-kustomize:
    name: Test Kustomize Overlays
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Run Kustomize Build for ${{ github.event.inputs.application }}
        run: |
          kustomize build ${{ github.event.inputs.application }}/overlays/ > output.yaml

      - name: Show Output Manifests
        run: cat output.yaml

      - name: Validate Kubernetes Manifests with kubeval
        run: |
          curl -sLO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          ./kubeval --ignore-missing-schemas output.yaml

      - name: Validate Manifests with Kubectl (Fallback)
        if: ${{ failure() }}
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl
          kubectl apply --dry-run=client -f output.yaml
